### ISSUE TITLE
5V RGB led not working

### ISSUE THREAD

**Issue by uhofemei** [01org/SmartHome-Demo#133] opened 2017-05-02 15:29 UTC
I connected a 5V chainable RGB led to the protoshield connector as described in the multi sensor Arduino 101 README. Unfortunately the light doesn't turn on.

**Comment by gvancuts** [comment] 2017-05-03 04:58
Do you have a LED attached to D3 as well? If so, does that one work as expected?

**Comment by qiuzhong** [comment] 2017-05-03 06:28
[Grove base shield](http://wiki.seeed.cc/Base_Shield_V2/) is required in the [ocf_multi_sensors](https://github.com/01org/SmartHome-Demo/tree/master/sensors/ocf_multi_sensors#sensor-wiring). Protoshield is not tested and I am not sure it can work on this shield connector (I have no such hardware in hand).

**Comment by uhofemei** [comment] 2017-05-03 15:53
I'm using a Grove shield. The flip switch is set to 5V. The chainable RGB led turns on briefly when I power cycle the device. It's connected to port D7.

**Comment by qiuzhong** [comment] 2017-05-04 01:12
I met the behavior that the RGB LED turns on briefly before. This is the intended behavior. The RGB value is initialized to [0,0,0], that's why the RGB LED turns off soon.  The RGB value can be updated by sending REST API server with POST method.

**Comment by gvancuts** [comment] 2017-05-10 04:37
This was confirmed to be functional, closing this issue.

**Closed by gvancuts** 2017-05-10 04:37 UTC
Labels: bug
