### ISSUE TITLE
Buzzer not functioning when button pressed

### ISSUE THREAD

**Issue by mjkadera** [01org/SmartHome-Demo#108] opened 2017-02-28 07:58 UTC
The buzzer does not make a sound when the button is pressed. The buzzer does function since it does make a noise when the motion board is restarted

**Comment by gvancuts** [comment] 2017-02-28 08:02
The following custom rule was added to the live system but did not work:
```
  "button":{
        "add":{
        },
        "update":[
            {
                "name":"value",
                "condition":"new_value === true",
                "actions":[
                    { "Type": "buzzer", "att": { "value": true }, "Event": "update" }
                ]
            },
            {
                "name":"value",
                "condition": "new_value === false",
                "actions":[
                    { "Type": "buzzer", "att": { "value": false }, "Event": "update" }
                ]
            }
        ],
        "remove":{
        }
    }
```

**Comment by nagineni** [comment] 2017-02-28 08:26
I have not tested this on the HW yet, but I quickly checked on my desktop env and the rule seems to be working fine.

$ SmartHome-Demo/ocf-servers/js-servers$ NODE_DEBUG=button  node button.js
```
BUTTON 3732: No mraa module:  Cannot find module 'mraa'
BUTTON 3732: Create button resource.
BUTTON 3732: register() resource successful
BUTTON 3732: Send the response:  true
```

$ SmartHome-Demo/ocf-servers/js-servers$ NODE_DEBUG=buzzer node buzzer.js
```
BUZZER 3716: No mraa module:  Cannot find module 'mraa'
BUZZER 3716: Create Buzzer resource.
BUZZER 3716: Update received. value:  true
BUZZER 3716: Send the response. value:  true
BUZZER 3716: Successfully notified observers.
```

$ SmartHome-Demo/gateway$ NODE_DEBUG=gateway-server node gateway-server.js
```
GATEWAY-SERVER 3681: Resource updated:{
    "id": "button",
    "value": true
}

GATEWAY-SERVER 3681: [{"Type":"button","Event":"update","att":{"id":"button","value":true}}]
GATEWAY-SERVER 3681: ----------------------------------------------
GATEWAY-SERVER 3681: Sending Update to buzzer resourceId:b675595e-bef8-47b7-a9eb-cea8b53ca0cc:/a/buzzer
GATEWAY-SERVER 3681: Resource updated:{
    "value": true,
    "id": "buzzer"
}
```

**Comment by nagineni** [comment] 2017-02-28 16:20
I checked it on the target HW and it's working fine for me. I tried with both button-toggle.js and button.js. In button.js case, you need to long press the button to change the state to true.

**Comment by gvancuts** [comment] 2017-03-01 00:13
Thanks for having verified this @nagineni! Maybe this is something related to our demo set-up. We have never got it to work despite all attempts. I have never actually been able to get the buzzer to beep, apart from when the board starts (or stops, I don't remember exactly). I even tried to change the default value on line [18](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/js-servers/buzzer.js#L18) from `false` o `true` but that did not work.

As a side question, how does the rule engine determine which device it should change in case there are multiple device with the same name (e.g. `buzzer`) but with different `id`?

**Comment by uhofemei** [comment] 2017-03-01 00:14
The buzzer can be triggered from Salvatore's smart home control app.

**Comment by gvancuts** [comment] 2017-03-01 00:27
I'm pretty sure we tried from @ttzeng 's [app](https://github.com/ttzeng/android-apps) but I'll need to double-check with @mjkadera tomorrow.

**Comment by qiuzhong** [comment] 2017-03-01 02:31
In fact, there is a bug that the smart-home-control app can't make the buzzer sensor work, see [smart-home-control issue#12](https://github.com/siovene/smart-home-control/issues/12)

**Comment by mjkadera** [comment] 2017-03-01 07:34
I did try it with @ttzeng 's app and we have the same results where the buzzer will just not trigger

**Comment by nagineni** [comment] 2017-03-02 15:17
> Thanks for having verified this @nagineni! Maybe this is something related to our demo set-up. We have never got it to work despite all attempts. I have never actually been able to get the buzzer to beep, apart from when the board starts (or stops, I don't remember exactly). I even tried to change the default value on line 18 from false o true but that did not work.

Can you check the server logs and see whether it is receiving the update request or not?
`$ NODE_DEBUG=buzzer node buzzer.js`

> As a side question, how does the rule engine determine which device it should change in case there are multiple device with the same name (e.g. buzzer) but with different id?

Currently the rules engine changes the state of the first discovered device always. We can change the functionality to define the device id + name in the rules, if needed.

**Comment by gvancuts** [comment] 2017-03-02 19:21
I don't have the system with me anymore, it's being shipped back to Oregon. I don't recall seeing these updates coming in but I'm not 100% anymore. It'd be good if @uhofemei could check that once the system is back in Oregon.

I think there was a also a point where two buzzers were reported by the IoT REST API Server. I don't know why but that made me wonder if part of the problem wasn't that the rule was set on the 'ghost' buzzer.

**Comment by uhofemei** [comment] 2017-03-06 17:03
I will take a look.

**Comment by gvancuts** [comment] 2017-03-07 09:10
> Currently the rules engine changes the state of the first discovered device always. We can change the
> functionality to define the device id + name in the rules, if needed.

Would that be a feature request to be implemented or is it something that is in place already but just not used yet in our default `rules.json` file?

**Comment by nagineni** [comment] 2017-03-08 12:58
> Would that be a feature request to be implemented or is it something that is in place already but just not used yet in our default rules.json file?

Code needs to be adjusted a bit in the gateway-server.js, so it's a feature request. :smile:

**Comment by gvancuts** [comment] 2017-03-08 13:44
Thanks @nagineni , I have filed #113 to track this.

**Comment by uhofemei** [comment] 2017-03-13 16:47
With https://github.com/01org/SmartHome-Demo/issues/113 merged, I think we can close this issue?

**Comment by gvancuts** [comment] 2017-03-13 17:10
These are separate. We still need to investigate why the buzzer does not function at all on the hardware kit that we use. The rule should be working well and the investigation should focus on trying to validate the buzzer hardware in isolation for now. Once that's cleared, we can test the rule again.

**Comment by uhofemei** [comment] 2017-03-13 17:16
OK understood. Once the demo is back in the lab, I will check this out.

**Comment by mjkadera** [comment] 2017-04-19 04:51
@kiendinh will test with a 5V connector on Arduino 101

**Comment by mjkadera** [comment] 2017-04-26 04:41
@uhofemei , Can you help take a look at this setup? @kiendinh was able to get it to work with 5V on the shield.

**Comment by uhofemei** [comment] 2017-04-28 15:19
I have not yet tried to trigger the buzzer on button push, but I can confirm the buzzer works using Tonny's companion app. It also triggers if motion is detected making for a good alarm system.

**Closed** 2017-05-09 18:30 UTC
Labels: bug
