### ISSUE TITLE
Fail install python dependencies while setting up SmartHome demo

### ISSUE THREAD

**Issue by haoxli** [01org/SmartHome-Demo#18] opened 2016-06-20 01:44 UTC
Hi
I’m setting up SmartHome Demo[1]  in Ostro[2], but there are two dependencies fail to install.
- [Icarus](https://github.com/tripzero/icarus) [pip install error]: libraries lapack not found in ['/usr/lib']
- [Twisted](https://twistedmatrix.com/) [pip install error]: /usr/lib/gcc/x86_64-ostro-linux/5.3.0/../../../../x86_64-ostro-linux/bin/ld: cannot find –lssp

Errors looks like the libssp.so which is part of gcc runtime is missing on the image. 

I make a workaround to build Twisted in Ubuntu, and then copy python packages to Ostro, it also work.
But for Icarus, there are more dependence libs, it does not work after copy them simply. 
 
So I still hope to get the way to install them directly in Ostro. Can  we resolve this dependence issue?
 
Thanks in advance.
 
[1] https://github.com/01org/SmartHome-Demo 
[2] https://download.ostroproject.org/builds/ostro-os/2016-05-31_12-21-10-build-459/images/intel-corei7-64/ostro-image-swupd-dev-intel-corei7-64.dsk.zip

**Comment by gvancuts** [comment] 2016-06-20 10:13
@uhofemei @kiendinh @nagineni can you please take a look?

**Comment by kiendinh** [comment] 2016-06-20 10:51
@haoxli I ran to problems with the latest Icarus, so I used the old Icarus version in the repository instead. As a workaround, you can do:
$ git checkout 258d533e4ba3e37fa1a9641c1529b22941eda97f
Then you'll see a py_modules.tar.gz included in the folder. Copy that to another location and checkout the latest master again. The tarball contains other modules with versions confirmed to worked with the SmartHome-Demo.

**Comment by nagineni** [comment] 2016-06-20 13:16
> Errors looks like the libssp.so which is part of gcc runtime is missing on the image. 

libssp.so is missing on the ostro dev image and causing the build failure. Please report a bug about missing libssp on the image.

**Comment by nagineni** [comment] 2016-06-20 13:21
> Then you'll see a py_modules.tar.gz included in the folder. Copy that to another location and checkout the latest master again. The tarball contains other modules with versions confirmed to worked with the SmartHome-Demo.

Tarball contains the pre-compiled version of python modules and that's the reason they are working fine.

**Comment by uhofemei** [comment] 2016-06-20 15:37
I opened a bug in the public project bug tracker. I would assign this bug to Kevron, but it seems Kevron hasn't created an account in public Jira yet.

Here's the link: https://ostroproject.org/jira/projects/OP/issues/OP-80

**Comment by gvancuts** [comment] 2016-06-20 15:54
We're not using that yet, can  you use https://github.com/ostroproject/ostro-os/issues instead?

**Comment by uhofemei** [comment] 2016-06-20 16:00
https://github.com/ostroproject/ostro-os/issues/127

**Comment by nagineni** [comment] 2016-07-13 13:33
Solar panel can be tested without the Icarus and other python modules now. Run the solar.js on edison and control the panel from the 3D UI or by setting the simulationMode property true/false using REST API server.

**Closed by nagineni** 2016-07-13 13:33 UTC

**Comment by uhofemei** [comment] 2016-07-13 20:05
:+1:
