### ISSUE TITLE
Replace Edison boards with Arduino 101 boards

### ISSUE THREAD

**Issue by mjkadera** [01org/SmartHome-Demo#130] opened 2017-04-19 05:04 UTC
Kien is working on this. Gas sensor is not able to migrate without adding another power source since the power requirement is over 3. Volts for the logic circuit. Will use the Edison to manage the gas

**Comment by mjkadera** [comment] 2017-04-19 05:07
Adding more resources, for example ZephyrJS to the Arduino 101 could be limited by space or is an OCF server issue. @poussa is this an OCF server issue or an issue with multiple property types

**Comment by kiendinh** [comment] 2017-04-19 05:07
All of the 3.3 V sensors have been migrated.
https://github.com/01org/SmartHome-Demo/pull/129

**Comment by mjkadera** [comment] 2017-04-26 04:33
@kiendinh is still working on this. 5 volt is still WIP. Will need to use an Edison to support these sensors.

We need to move a few of the sensors to JavaScript to help test the comms stack. @mjkadera and @gvancuts  to add a new enhancement for this request.

**Comment by uhofemei** [comment] 2017-04-28 15:34
This is work in progress. I have all the parts and just need to flash the device with Kien's code and swap out the Edison with the A101 on Monday.

**Comment by uhofemei** [comment] 2017-05-02 15:15
The multi sensor solution on Arduino 101 doesn't run stable. I'm able to access temperature, ambient light and motion for 2 minutes or less before the resources disappear. I have reason to believe this is caused by Zephyr crashing and not the BLE interface going down. This is for the reason that our "other" BLE solution being the power meter runs stable after the multi sensor solution has gone down.

**Comment by gvancuts** [comment] 2017-05-17 09:23
@uhofemei , I would like to close this feature request as done and continue tracking the stability issue through #140 , are you OK with that? Or are there other problems not yet captured in other issues?

**Comment by uhofemei** [comment] 2017-05-17 12:59
I'm OK with that.

**Comment by gvancuts** [comment] 2017-05-17 14:14
We now have a number of smart sensors running on Arduino/Genuino 101 hence closing this feature request. If new sensors should be developed, a new feature request will need to be created.

**Closed by gvancuts** 2017-05-17 14:14 UTC
Labels: enhancement
